### ISSUE TITLE
I found a bug in .env.example.

### ISSUE THREAD

**Issue by YangAi** [liyu001989/laravel-api-starter#4]
Thanks for your project! It helps me a lot. However, I think I might find a bug in the .env.example file.

`JWT_SECRET=
# 一天过期，一周可刷新
JWT_TTL=86300
JWT_REFRESH_TTL=20160`

I believe the JWT_TTL is supposed to be 1440, instead of 86300, since this param is measured by minutes, not seconds.

**Comment by liyu001989** [comment]
You are right，thanks
